version: '3'

services:
  mysql:
    image: mysql:8
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=hogehoge
      - MYSQL_USER=add
      - MYSQL_PASSWORD=password
